# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

# ---- Natron

# asset step
settings.tk-multi-publish2.natron.asset_step:
  collector: "{self}/collector.py:{engine}/tk-multi-publish2/basic/collector.py"
  collector_settings:
      Work Template: natron_asset_work
  publish_plugins:
  - name: Publish to Shotgun
    hook: "{self}/publish_file.py"
    settings: {}
  - name: Upload for review
    hook: "{self}/upload_version.py"
    settings: {}
  - name: Begin file versioning
    hook: "{engine}/tk-multi-publish2/basic/start_version_control.py"
    settings: {}
  - name: Publish to Shotgun
    hook: "{self}/publish_file.py:{engine}/tk-multi-publish2/basic/publish_session.py"
    settings:
        Publish Template: natron_asset_publish
  # - name: Submit for Review
  #   hook: "{engine}/tk-multi-publish2/basic/submit_for_review.py"
  #   settings: {}
  help_url: *help_url
  location: "@apps.tk-multi-publish2.location"

# shot step
settings.tk-multi-publish2.natron.shot_step:
  collector: "{self}/collector.py:{engine}/tk-multi-publish2/basic/collector.py"
  collector_settings:
      Work Template: natron_shot_work
  publish_plugins:
  - name: Publish to Shotgun
    hook: "{self}/publish_file.py"
    settings: {}
  - name: Upload for review
    hook: "{self}/upload_version.py"
    settings: {}
  - name: Begin file versioning
    hook: "{engine}/tk-multi-publish2/basic/start_version_control.py"
    settings: {}
  - name: Publish to Shotgun
    hook: "{self}/publish_file.py:{engine}/tk-multi-publish2/basic/publish_session.py"
    settings:
        Publish Template: natron_shot_publish
  # - name: Submit for Review
  #   hook: "{engine}/tk-multi-publish2/basic/submit_for_review.py"
  #   settings: {}
  # - name: Update Flame Clip
  #   hook: "{engine}/tk-multi-publish2/basic/natron_update_flame_clip.py"
  #   settings:
  #       Flame Clip Template: flame_shot_clip
  help_url: *help_url
  location: "@apps.tk-multi-publish2.location"
