# Copyright (c) 2015 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

# Author: Diego Garcia Huerta
# Contact: https://www.linkedin.com/in/diegogh/
#
# YOU SHOULD MERGE these entries into your template.yml configuration file, as
# THIS FILE BY ITSELF WILL NOT WORK 
# These are the additions to the template.yml to get natron engine up and 
# running with the default tk-apps


keys:
    natron.output:
        alias: output
        type: str
        filter_by: alphanumeric

paths:
    #
    # Natron
    #

    # asset based
    
    # define the location of a work area
    asset_work_area_natron:
        definition: '@asset_root/work/natron'
        root_name: 'primary'

    # define the location of a publish area
    asset_publish_area_natron:
        definition: '@asset_root/publish/natron'
        root_name: 'primary'

    # The location of WIP script files
    natron_asset_work:
        definition: '@asset_root/work/natron/{name}.v{version}.ntp'
        root_name: 'primary'

    # The location of backups of WIP files
    natron_asset_snapshot:
        definition: '@asset_root/work/natron/snapshots/{name}.v{version}.{timestamp}.ntp'
        root_name: 'primary'

    # The location of published natron script files
    natron_asset_publish:
        definition: '@asset_root/publish/natron/{name}.v{version}.ntp'
        root_name: 'primary'

    # write node outputs
    natron_asset_render_mono_dpx:
        definition: '@asset_root/work/images/{name}/v{version}/{width}x{height}/{Shot}_{name}_{natron.output}_v{version}.{SEQ}.dpx'
        root_name: 'primary'

    natron_asset_render_pub_mono_dpx:
        definition: '@asset_root/publish/elements/{name}/v{version}/{width}x{height}/{Shot}_{name}_{natron.output}_v{version}.{SEQ}.dpx'
        root_name: 'primary'

    natron_asset_render_stereo:
        definition: '@asset_root/work/images/{name}/v{version}/{width}x{height}/{Shot}_{name}_{natron.output}_{eye}_v{version}.{SEQ}.exr'
        root_name: 'primary'

    natron_asset_render_pub_stereo:
        definition: '@asset_root/publish/elements/{name}/v{version}/{width}x{height}/{Shot}_{name}_{natron.output}_{eye}_v{version}.{SEQ}.exr'
        root_name: 'primary'
    
    # review output
    asset_quicktime_quick:
        definition: '@asset_root/review/quickdaily/{Shot}_{name}_{iteration}.mov'
        root_name: 'primary'

    natron_asset_render_movie:
        definition: '@asset_root/review/{Shot}_{name}_v{version}.mov'
        root_name: 'primary'


    # shot based
    
    # define the location of a work area
    shot_work_area_natron:
        definition: '@shot_root/work/natron'
        root_name: 'primary'

    # define the location of a publish area
    shot_publish_area_natron:
        definition: '@shot_root/publish/natron'
        root_name: 'primary'

    # The location of WIP script files
    natron_shot_work:
        definition: '@shot_root/work/natron/{name}.v{version}.ntp'
        root_name: 'primary'

    # The location of backups of WIP files
    natron_shot_snapshot:
        definition: '@shot_root/work/natron/snapshots/{name}.v{version}.{timestamp}.ntp'
        root_name: 'primary'

    # The location of published natron script files
    natron_shot_publish:
        definition: '@shot_root/publish/natron/{name}.v{version}.ntp'
        root_name: 'primary'

    # write node outputs
    natron_shot_render_mono_dpx:
        definition: '@shot_root/work/images/{name}/v{version}/{width}x{height}/{Shot}_{name}_{natron.output}_v{version}.{SEQ}.dpx'
        root_name: 'primary'

    natron_shot_render_pub_mono_dpx:
        definition: '@shot_root/publish/elements/{name}/v{version}/{width}x{height}/{Shot}_{name}_{natron.output}_v{version}.{SEQ}.dpx'
        root_name: 'primary'

    natron_shot_render_stereo:
        definition: '@shot_root/work/images/{name}/v{version}/{width}x{height}/{Shot}_{name}_{natron.output}_{eye}_v{version}.{SEQ}.exr'
        root_name: 'primary'

    natron_shot_render_pub_stereo:
        definition: '@shot_root/publish/elements/{name}/v{version}/{width}x{height}/{Shot}_{name}_{natron.output}_{eye}_v{version}.{SEQ}.exr'
        root_name: 'primary'
    
    # review output
    shot_quicktime_quick:
        definition: '@shot_root/review/quickdaily/{Shot}_{name}_{iteration}.mov'
        root_name: 'primary'

    natron_shot_render_movie:
        definition: '@shot_root/review/{Shot}_{name}_v{version}.mov'
        root_name: 'primary'

